// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.5
// source: inscription/v1/inscription.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Inscription_CreateUser_FullMethodName = "/api.inscription.v1.Inscription/CreateUser"
)

// InscriptionClient is the client API for Inscription service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InscriptionClient interface {
	CreateUser(ctx context.Context, in *CreateUserInfo, opts ...grpc.CallOption) (*UserInfoResponse, error)
}

type inscriptionClient struct {
	cc grpc.ClientConnInterface
}

func NewInscriptionClient(cc grpc.ClientConnInterface) InscriptionClient {
	return &inscriptionClient{cc}
}

func (c *inscriptionClient) CreateUser(ctx context.Context, in *CreateUserInfo, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, Inscription_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InscriptionServer is the server API for Inscription service.
// All implementations must embed UnimplementedInscriptionServer
// for forward compatibility
type InscriptionServer interface {
	CreateUser(context.Context, *CreateUserInfo) (*UserInfoResponse, error)
	mustEmbedUnimplementedInscriptionServer()
}

// UnimplementedInscriptionServer must be embedded to have forward compatible implementations.
type UnimplementedInscriptionServer struct {
}

func (UnimplementedInscriptionServer) CreateUser(context.Context, *CreateUserInfo) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedInscriptionServer) mustEmbedUnimplementedInscriptionServer() {}

// UnsafeInscriptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InscriptionServer will
// result in compilation errors.
type UnsafeInscriptionServer interface {
	mustEmbedUnimplementedInscriptionServer()
}

func RegisterInscriptionServer(s grpc.ServiceRegistrar, srv InscriptionServer) {
	s.RegisterService(&Inscription_ServiceDesc, srv)
}

func _Inscription_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InscriptionServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inscription_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InscriptionServer).CreateUser(ctx, req.(*CreateUserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Inscription_ServiceDesc is the grpc.ServiceDesc for Inscription service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inscription_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.inscription.v1.Inscription",
	HandlerType: (*InscriptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Inscription_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inscription/v1/inscription.proto",
}
