// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v3.21.5
// source: inscription/v1/inscription.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInscriptionCreateUser = "/api.inscription.v1.Inscription/CreateUser"

type InscriptionHTTPServer interface {
	CreateUser(context.Context, *CreateUserInfo) (*UserInfoResponse, error)
}

func RegisterInscriptionHTTPServer(s *http.Server, srv InscriptionHTTPServer) {
	r := s.Route("/")
	r.GET("/api/collection/ranking", _Inscription_CreateUser0_HTTP_Handler(srv))
}

func _Inscription_CreateUser0_HTTP_Handler(srv InscriptionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateUserInfo
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInscriptionCreateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUser(ctx, req.(*CreateUserInfo))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserInfoResponse)
		return ctx.Result(200, reply)
	}
}

type InscriptionHTTPClient interface {
	CreateUser(ctx context.Context, req *CreateUserInfo, opts ...http.CallOption) (rsp *UserInfoResponse, err error)
}

type InscriptionHTTPClientImpl struct {
	cc *http.Client
}

func NewInscriptionHTTPClient(client *http.Client) InscriptionHTTPClient {
	return &InscriptionHTTPClientImpl{client}
}

func (c *InscriptionHTTPClientImpl) CreateUser(ctx context.Context, in *CreateUserInfo, opts ...http.CallOption) (*UserInfoResponse, error) {
	var out UserInfoResponse
	pattern := "/api/collection/ranking"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInscriptionCreateUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
