// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/internal/biz"
	"backend/internal/conf"
	"backend/internal/data"
	"backend/internal/server"
	"backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	engine := data.NewPostgres(confData)
	dataData, cleanup, err := data.NewData(confData, logger, engine)
	if err != nil {
		return nil, nil, err
	}
	inscriptionRepo := data.NewInscriptionRepo(dataData, logger)
	inscriptionUsecase := biz.NewInscriptionUsecase(inscriptionRepo, logger)
	inscriptionService := service.NewInscriptionService(inscriptionUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, inscriptionService, logger)
	httpServer := server.NewHTTPServer(confServer, inscriptionService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
