version: "3.1"
services:
  swift-indexer:
    container_name: swift-indexer
    restart: always
    image: swift-indexer:0.1.0
    build:
      context: ./
      dockerfile: Dockerfile
    # ports:
    #   - "8081:8081"
    depends_on:
      - db-init
    entrypoint:
      [
        "swift-indexer",
        "sync",
        "--start-block=${START_BLOCK:-0}",
        "--endpoint-url=${ENDPOINT_URL:-https://mainnet.era.zksync.io}",
      ]
    environment:
      DATABASE_URL: postgres://admin:secure@postgres-swift-indexer:5432/swift-indexer-dev?sslmode=disable
    networks:
      - SIP
  db-init:
    image: willsquire/diesel-cli:latest
    networks:
      - SIP
    environment:
      DATABASE_URL: postgres://admin:secure@postgres-swift-indexer:5432/swift-indexer-dev?sslmode=disable
    volumes:
      - ./migrations:/app/migrations
    command: ["migration", "run"]

networks:
  SIP:
    external: true
