[package]
name = "substreams-swift"
version = "0.1.0"
description = "Substream for Swift"
edition = "2021"
repository = "https://github.com/storswiftlabs/eth-inscription-protocol.git"
license = "Apache 2.0"

[lib]
name = "substreams"
crate-type = ["cdylib"]

[dependencies]
num-bigint = "0.4.3"
ethabi = "17"
hex-literal = "0.3.4"
prost = "0.11"
# Use latest from https://crates.io/crates/substreams
substreams = "0.5"
serde_json = "1.0.104"
serde = { version = "1.0.183", features = ["derive"] }
hex = "0.4.3"
prost-types = "0.11.9"
base64 = "0.21.2"

# Required so that ethabi > ethereum-types build correctly under wasm32-unknown-unknown
[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[build-dependencies]
anyhow = "1"
substreams-ethereum = "0.9.0"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
